create table teacher (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    age int4 NOT NULL check ( age > 18 ),
    email varchar(255) NOT NULL check ( char_length(email) >= 2 and char_length(email) <= 40),
    first_name varchar(255) NOT NULL check ( char_length(first_name) >= 2 and char_length(first_name) <= 40),
    last_name varchar(255) NOT NULL check ( char_length(last_name) >= 2 and char_length(last_name) <= 40),
    school_subject varchar(255) NOT NULL check ( char_length(school_subject) >= 2 and char_length(school_subject) <= 40),
    CONSTRAINT teacher_pkey PRIMARY KEY (id)
);

create table student (
    id int8 NOT NULL,
    age int4 NOT NULL check ( age > 18 ),
    email varchar(255) NOT NULL check ( char_length(email) >= 2 and char_length(email) <= 40),
    field_of_study varchar(255) NOT NULL check ( char_length(field_of_study) >= 2 and char_length(field_of_study) <= 40),
    first_name varchar(255) NOT NULL check ( char_length(first_name) >= 2 and char_length(first_name) <= 40),
    last_name varchar(255) NOT NULL check ( char_length(last_name) >= 2 and char_length(last_name) <= 40),
    CONSTRAINT student_pkey PRIMARY KEY (id)
);

create table teachers_students (
    id_teacher int8 NOT NULL,
    id_student int8 NOT NULL,
    CONSTRAINT teachers_students_pkey PRIMARY KEY (id_teacher, id_student),
    CONSTRAINT fk_teacher FOREIGN KEY (id_teacher) REFERENCES sample_schema.teacher(id),
    CONSTRAINT fk_student FOREIGN KEY (id_student) REFERENCES sample_schema.student(id)
);